# Generated by Django 3.1 on 2020-08-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type',
        ),
    ]
