# Generated by Django 3.1 on 2020-08-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quarters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=15)),
                ('Lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('quarter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quarters.quarter')),
            ],
        ),
    ]
